export const name = `Engr. Suleiman H. Adamu FNSE, FAEng.`;
export const position = `Minister of Water Resources`;

export const citation = `
Engr. Suleiman Hussaini Adamu FNSE, FAEng. is the Minister of Water Resources with a rich pedigree in the public and private sectors of Nigeria's development. He obtained a Bachelor of Engineering degree in Civil Engineering from Ahmadu Bello University, Zaria, Nigeria in 1984 and Master of Science degree in Project Management from the University of Reading, UK in 2004. He was Winner, Nigeria Ports Authority Prize for the Best Final Year Student in Civil Engineering in 1984. 

\nHe commenced his career in the Nigerian Public Sector and later co-founded a private engineering consultancy firm with core competence in Civil, Electrical, Mechanical and Environmental Engineering Consultancy based in Kaduna, Nigeria.  
\nHe has delivered many engineering and infrastructural projects in Nigeria, including roads, water supply, public & private buildings and many social development projects in the health, education and agriculture sectors for the defunct Petroleum (Special) Trust Fund (PTF). 

\nEngr. Suleiman was President of the Association of Consulting Engineering in Nigeria (ACEN) from 2015-2017. He was a Council Member of the Council for the Regulation of Engineering in Nigeria (COREN). He is also a Fellow of the Nigerian Society of Engineers (FNSE), Member American Society of Civil Engineers (MASCE), Fellow Nigerian Institution of Water Engineers (FNIWE), Fellow Nigerian Association of Hydrogeologists (FNAH), Fellow Nigeria Mining & Geosciences Society (FNMGS), Fellow Nigerian Academy of Engineering (FAEng.) and Fellow Academy of Natural Science and Engineering in Nigeria (FANSE). He has served in various Committees of the Nigeria Society of Engineers (NSE) for the past 2 decades.  

\nSince assuming office as the Minister of Water Resources in November 2015, Engr. Suleiman has brought his diverse wealth of professional engineering and business experience to bear on the Nigerian Water Sector. His visionary leadership has catalysed positive impact in the Sector, especially with the approval in 2016 of the Water Resources Roadmap, Water Resources Bill, National Water Resources Policy and the National Irrigation & Drainage Policy by the Federal Executive Council.  
\nHe is currently leading a vigorous effort to ensure that Nigeria attains the UN Sustainable Development Goals, specifically Goal 6, by collaborating with various stakeholders under the programme “Partnership for Expanded Water, Sanitation and Hygiene” (PEWASH) which he initiated in 2016. Engr. Suleiman also anchored the process that led to Federal Executive Council (FEC) approval of a National Water, Sanitation and Hygiene (WASH) Action Plan in February 2018 and declaration of State of Emergency on the sector by President Muhammadu Buhari in November 2018, the first of such in Africa.  He has since 2019 championed a national campaign to end Open Defecation in Nigeria by 2025 and has been the leading promoter and architect of the Open Defecation Free (ODF) Nigeria Roadmap and Presidential Executive Order No. 9, which gives legal and top-level political backing to the ODF Campaign.
\nHis unrelenting commitment to the implementation of the National WASH Action Plan has successfully leveraged a $700million World Bank facility for a newly designed Sustainable Urban and Rural WASH (SURWASH) Project, that will support eligible states of the Federation to invest more in WASH projects and services.
\nEngr. Adamu is also currently pushing the process of establishing a WASH Fund for Nigeria, that is envisaged to be the largest in Africa.
\nHe successfully midwifed commencement and implementation of the $495million World Bank assisted Transforming Irrigation Management in Nigeria (TRIMING) Project for the rehabilitation and expansion of five (5) major irrigation schemes, that also aim to revolutionize management of irrigation infrastructures into country. 
\nHe was a key player in the promulgation of Executive Order No. 5 in February 2018, towards maximising local content in Nigeria's infrastructure and economic development\nHe is happily married and blessed with 4 children.
\nHe was the immediate past Chairman, Council of Ministers of the Niger Basin Authority (NBA), the immediate past Chairman Council of Ministers of the Lake Chad Basin Commission (LCBC) and the immediate past Vice Chairman African Ministers’ Council on Water (AMCOW) representing West Africa.
\nHe is a member of Kazaure Emirate Council and holds the traditional title Galadiman Kazaure. He is an avid golfer and was Captain of Kaduna Golf Club from 2014-2016. 
\nHe is happily married and blessed with 4 children. 
\nAs his tenure under the President Muhammadu Buhari’s Administration comes to end on 28th May, 2023, the Management and Staff of the Federal Ministry of Water Resources, wish him a fulfilling and impactful rest from Office. `;
