import "./globals.css";
import BigNav from "./components/Navbar";
import Herosection from "./components/Herosection";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BigNav />
        <Herosection />
        {children}
      </body>
    </html>
  );
}
